namespace OpenNFS.XdrGen.Emission
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using OpenNFS.XdrGen.Model;

    internal sealed class XdrEmissionTypeSupport
    {
        private readonly XdrEmissionContext context;

        internal XdrEmissionTypeSupport(XdrEmissionContext context)
        {
            this.context = context;
        }

        internal void EmitConstantsClass()
        {
            List<XdrConstDefinition> constants = context.Documents
                .SelectMany(document => document.Definitions)
                .OfType<XdrConstDefinition>()
                .ToList();

            if (constants.Count < 1)
            {
                return;
            }

            CodeWriter writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("#pragma warning disable CS8981");
            writer.AppendLine("namespace " + context.Mapping.OutputNamespace);
            writer.AppendLine("{");
            writer.AppendLine("    /// <summary>");
            writer.AppendLine("    /// Defines emitted XDR numeric constants for the " + XdrEmissionContext.EscapeXml(context.Mapping.Id) + " corpus.");
            writer.AppendLine("    /// </summary>");
            writer.AppendLine("    public static class " + XdrEmissionContext.EscapeIdentifier(context.ConstantsTypeName));
            writer.AppendLine("    {");

            foreach (XdrConstDefinition constant in constants)
            {
                writer.AppendLine("        /// <summary>");
                writer.AppendLine("        /// Represents the XDR constant <c>" + XdrEmissionContext.EscapeXml(constant.Name) + "</c>.");
                writer.AppendLine("        /// </summary>");
                writer.AppendLine("        public const ulong " + XdrEmissionContext.EscapeIdentifier(constant.Name) + " = " + context.Symbols.ResolveNumericLiteral(constant.Name) + ";");
                writer.AppendLine();
            }

            writer.RemoveTrailingBlankLine();
            writer.AppendLine("    }");
            writer.AppendLine("}");
            writer.AppendLine("#pragma warning restore CS8981");

            context.AddGeneratedFile(context.ConstantsTypeName, writer.ToString());
        }

        internal void EmitTypedefDefinition(XdrTypedefDefinition typedefDefinition)
        {
            string aliasName = typedefDefinition.Declarator.Identifier;

            if (XdrEmissionContext.IsAnonymousTypeSpecifier(typedefDefinition.TypeSpecifier))
            {
                EmitTypeFromSpecifier(aliasName, typedefDefinition.TypeSpecifier);
                return;
            }

            if (typedefDefinition.TypeSpecifier is XdrQualifiedTypeSpecifier qualifiedTypeSpecifier
                && string.Equals(qualifiedTypeSpecifier.Name, aliasName, StringComparison.Ordinal)
                && typedefDefinition.Declarator.Kind == XdrDeclaratorKind.Pointer)
            {
                return;
            }

            EmitAliasType(aliasName, typedefDefinition.TypeSpecifier, typedefDefinition.Declarator);
        }

        internal void EmitTopLevelTypeDefinition(XdrTypeDefinition typeDefinition)
        {
            switch (typeDefinition.TypeSpecifier)
            {
                case XdrEnumTypeSpecifier enumTypeSpecifier:
                    EmitNamedTopLevelType(enumTypeSpecifier.Name, typeDefinition.TypeSpecifier);
                    break;

                case XdrStructTypeSpecifier structTypeSpecifier:
                    EmitNamedTopLevelType(structTypeSpecifier.Name, typeDefinition.TypeSpecifier);
                    break;

                case XdrUnionTypeSpecifier unionTypeSpecifier:
                    EmitNamedTopLevelType(unionTypeSpecifier.Name, typeDefinition.TypeSpecifier);
                    break;

                default:
                    throw new InvalidDataException("Unsupported top-level XDR type definition for emission: " + typeDefinition.TypeSpecifier.GetType().FullName);
            }
        }

        internal void EmitProgramDefinition(XdrProgramDefinition programDefinition)
        {
            string typeName = programDefinition.Name + "_Program";
            CodeWriter writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("#pragma warning disable CS8981");
            writer.AppendLine("namespace " + context.Mapping.OutputNamespace);
            writer.AppendLine("{");
            writer.AppendLine("    /// <summary>");
            writer.AppendLine("    /// Defines emitted numeric identifiers for the XDR program <c>" + XdrEmissionContext.EscapeXml(programDefinition.Name) + "</c>.");
            writer.AppendLine("    /// </summary>");
            writer.AppendLine("    public static class " + XdrEmissionContext.EscapeIdentifier(typeName));
            writer.AppendLine("    {");
            writer.AppendLine("        /// <summary>");
            writer.AppendLine("        /// Gets the numeric program identifier.");
            writer.AppendLine("        /// </summary>");
            writer.AppendLine("        public const ulong Program = " + context.Symbols.ResolveExpressionLiteral(programDefinition.ValueExpression) + ";");
            writer.AppendLine();

            foreach (XdrVersionDefinition version in programDefinition.Versions)
            {
                string versionFieldName = "Version_" + version.Name;
                writer.AppendLine("        /// <summary>");
                writer.AppendLine("        /// Gets the numeric version identifier for <c>" + XdrEmissionContext.EscapeXml(version.Name) + "</c>.");
                writer.AppendLine("        /// </summary>");
                writer.AppendLine("        public const ulong " + XdrEmissionContext.EscapeIdentifier(versionFieldName) + " = " + context.Symbols.ResolveExpressionLiteral(version.ValueExpression) + ";");
                writer.AppendLine();

                foreach (XdrProcedureDefinition procedure in version.Procedures)
                {
                    string procedureFieldName = "Procedure_" + version.Name + "_" + procedure.Name;
                    writer.AppendLine("        /// <summary>");
                    writer.AppendLine("        /// Gets the numeric procedure identifier for <c>" + XdrEmissionContext.EscapeXml(procedure.Name) + "</c> in version <c>" + XdrEmissionContext.EscapeXml(version.Name) + "</c>.");
                    writer.AppendLine("        /// </summary>");
                    writer.AppendLine("        public const ulong " + XdrEmissionContext.EscapeIdentifier(procedureFieldName) + " = " + context.Symbols.ResolveExpressionLiteral(procedure.ValueExpression) + ";");
                    writer.AppendLine();
                }
            }

            writer.RemoveTrailingBlankLine();
            writer.AppendLine("    }");
            writer.AppendLine("}");
            writer.AppendLine("#pragma warning restore CS8981");

            context.AddGeneratedFile(typeName, writer.ToString());
        }

        internal void EmitTypeFromSpecifier(string typeName, XdrTypeSpecifier typeSpecifier)
        {
            if (context.GeneratedFilesByTypeName.ContainsKey(typeName))
            {
                return;
            }

            switch (typeSpecifier)
            {
                case XdrEnumTypeSpecifier enumTypeSpecifier:
                    RegisterEmittedTypeKind(typeName, EmittedTypeKind.Enum);
                    EmitEnumType(typeName, enumTypeSpecifier);
                    break;

                case XdrStructTypeSpecifier structTypeSpecifier:
                    RegisterEmittedTypeKind(typeName, EmittedTypeKind.Class);
                    EmitStructType(typeName, structTypeSpecifier);
                    break;

                case XdrUnionTypeSpecifier unionTypeSpecifier:
                    RegisterEmittedTypeKind(typeName, EmittedTypeKind.Class);
                    EmitUnionType(typeName, unionTypeSpecifier);
                    break;

                default:
                    throw new InvalidDataException("Unsupported XDR type specifier for emission: " + typeSpecifier.GetType().FullName);
            }
        }

        internal void EmitClassType(
            string typeName,
            string summary,
            IReadOnlyList<PropertyDefinition> properties,
            Action<CodeWriter>? appendMembers = null)
        {
            CodeWriter writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("#pragma warning disable CS8981");
            writer.AppendLine("namespace " + context.Mapping.OutputNamespace);
            writer.AppendLine("{");
            writer.AppendLine("    using System;");
            writer.AppendLine("    using OpenNFS.Rpc.Xdr;");
            writer.AppendLine();
            writer.AppendLine("    /// <summary>");
            writer.AppendLine("    /// " + summary);
            writer.AppendLine("    /// </summary>");
            writer.AppendLine("    public sealed class " + XdrEmissionContext.EscapeIdentifier(typeName));
            writer.AppendLine("    {");

            foreach (PropertyDefinition property in properties)
            {
                writer.AppendLine("        /// <summary>");
                writer.AppendLine("        /// " + property.Summary);
                writer.AppendLine("        /// </summary>");
                writer.AppendLine("        public " + property.TypeName + " " + XdrEmissionContext.EscapeIdentifier(property.Name) + " { get; set; }");
                writer.AppendLine();
            }

            if (appendMembers is not null)
            {
                appendMembers(writer);
            }

            writer.RemoveTrailingBlankLine();
            writer.AppendLine("    }");
            writer.AppendLine("}");
            writer.AppendLine("#pragma warning restore CS8981");

            context.AddGeneratedFile(typeName, writer.ToString());
        }

        internal PropertyDefinition CreatePropertyDefinition(
            string ownerTypeName,
            XdrTypeSpecifier memberTypeSpecifier,
            XdrDeclarator declarator,
            ISet<string> usedPropertyNames,
            string summary)
        {
            string uniquePropertyName = XdrEmissionContext.GetUniquePropertyName(ownerTypeName, declarator.Identifier, usedPropertyNames);
            CSharpTypeReference propertyType = context.Symbols.ResolveTypeReference(ownerTypeName, memberTypeSpecifier, declarator);
            CodecValueDescriptor valueDescriptor = context.Symbols.ResolveCodecValueDescriptor(ownerTypeName, memberTypeSpecifier, declarator);
            return new PropertyDefinition(
                name: uniquePropertyName,
                wireName: declarator.Identifier,
                typeReference: propertyType,
                valueDescriptor: valueDescriptor,
                declarator: declarator,
                summary: summary);
        }

        private void RegisterEmittedTypeKind(string typeName, EmittedTypeKind typeKind)
        {
            if (context.DeclaredTypeKinds.TryGetValue(typeName, out EmittedTypeKind existingKind))
            {
                if (existingKind != typeKind)
                {
                    throw new InvalidDataException("Duplicate XDR type name '" + typeName + "' resolves to conflicting emitted kinds.");
                }

                return;
            }

            context.DeclaredTypeKinds.Add(typeName, typeKind);
        }

        private void EmitNamedTopLevelType(string? typeName, XdrTypeSpecifier typeSpecifier)
        {
            if (string.IsNullOrWhiteSpace(typeName))
            {
                throw new InvalidDataException("Top-level XDR type definitions must have explicit names for emission.");
            }

            EmitTypeFromSpecifier(typeName, typeSpecifier);
        }

        private void EmitEnumType(string typeName, XdrEnumTypeSpecifier enumTypeSpecifier)
        {
            CodeWriter writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("#pragma warning disable CS8981");
            writer.AppendLine("namespace " + context.Mapping.OutputNamespace);
            writer.AppendLine("{");
            writer.AppendLine("    /// <summary>");
            writer.AppendLine("    /// Represents the XDR enum <c>" + XdrEmissionContext.EscapeXml(typeName) + "</c>.");
            writer.AppendLine("    /// </summary>");
            writer.AppendLine("    public enum " + XdrEmissionContext.EscapeIdentifier(typeName) + " : int");
            writer.AppendLine("    {");

            foreach (XdrEnumMember member in enumTypeSpecifier.Members)
            {
                writer.AppendLine("        /// <summary>");
                writer.AppendLine("        /// Represents the XDR enum member <c>" + XdrEmissionContext.EscapeXml(member.Name) + "</c>.");
                writer.AppendLine("        /// </summary>");
                writer.AppendLine("        " + XdrEmissionContext.EscapeIdentifier(member.Name) + " = " + context.Symbols.ResolveExpressionLiteral(member.ValueExpression) + ",");
                writer.AppendLine();
            }

            writer.RemoveTrailingBlankLine();
            writer.AppendLine("    }");
            writer.AppendLine("}");
            writer.AppendLine("#pragma warning restore CS8981");

            context.AddGeneratedFile(typeName, writer.ToString());
            context.Codecs.EmitEnumCodecType(typeName);
        }

        private void EmitStructType(string typeName, XdrStructTypeSpecifier structTypeSpecifier)
        {
            List<PropertyDefinition> properties = new List<PropertyDefinition>();
            HashSet<string> usedPropertyNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (XdrFieldDeclaration field in structTypeSpecifier.Fields)
            {
                properties.Add(CreatePropertyDefinition(
                    ownerTypeName: typeName,
                    memberTypeSpecifier: field.TypeSpecifier,
                    declarator: field.Declarator,
                    usedPropertyNames: usedPropertyNames,
                    summary: "Gets or sets the XDR field <c>" + XdrEmissionContext.EscapeXml(field.Declarator.Identifier) + "</c>."));
            }

            EmitClassType(
                typeName,
                "Represents the XDR struct <c>" + XdrEmissionContext.EscapeXml(typeName) + "</c>.",
                properties,
                writer => context.Codecs.AppendStructCodecMembers(writer, typeName, properties));
        }

        private void EmitUnionType(string typeName, XdrUnionTypeSpecifier unionTypeSpecifier)
        {
            List<PropertyDefinition> properties = new List<PropertyDefinition>();
            List<UnionArmDefinition> arms = new List<UnionArmDefinition>();
            HashSet<string> usedPropertyNames = new HashSet<string>(StringComparer.Ordinal);
            XdrDeclarator discriminantDeclarator = new XdrDeclarator(
                unionTypeSpecifier.SwitchName,
                XdrDeclaratorKind.Identifier,
                null);
            PropertyDefinition discriminantProperty = CreatePropertyDefinition(
                ownerTypeName: typeName,
                memberTypeSpecifier: unionTypeSpecifier.SwitchType,
                declarator: discriminantDeclarator,
                usedPropertyNames: usedPropertyNames,
                summary: "Gets or sets the union discriminant <c>" + XdrEmissionContext.EscapeXml(unionTypeSpecifier.SwitchName) + "</c>.");
            properties.Add(discriminantProperty);

            foreach (XdrUnionArm arm in unionTypeSpecifier.Arms)
            {
                if (arm.Declaration is null)
                {
                    continue;
                }

                string uniquePropertyName = XdrEmissionContext.GetUniquePropertyName(typeName, arm.Declaration.Declarator.Identifier, usedPropertyNames);
                CSharpTypeReference propertyType = context.Symbols.ResolveTypeReference(typeName, arm.Declaration.TypeSpecifier, arm.Declaration.Declarator);
                string caseSummary = arm.IsDefault
                    ? "default"
                    : string.Join(", ", arm.CaseLabels.Select(label => "<c>" + XdrEmissionContext.EscapeXml(label) + "</c>"));

                PropertyDefinition armProperty = new PropertyDefinition(
                    name: uniquePropertyName,
                    wireName: arm.Declaration.Declarator.Identifier,
                    typeReference: propertyType,
                    valueDescriptor: context.Symbols.ResolveCodecValueDescriptor(typeName, arm.Declaration.TypeSpecifier, arm.Declaration.Declarator),
                    declarator: arm.Declaration.Declarator,
                    summary: "Gets or sets the union arm <c>" + XdrEmissionContext.EscapeXml(arm.Declaration.Declarator.Identifier) + "</c> selected by " + caseSummary + ".");
                properties.Add(armProperty);
                arms.Add(new UnionArmDefinition(armProperty, arm.CaseLabels, arm.IsDefault));
            }

            EmitClassType(
                typeName,
                "Represents the XDR union <c>" + XdrEmissionContext.EscapeXml(typeName) + "</c>.",
                properties,
                writer => context.Codecs.AppendUnionCodecMembers(writer, typeName, discriminantProperty, arms));
        }

        private void EmitAliasType(string typeName, XdrTypeSpecifier typeSpecifier, XdrDeclarator declarator)
        {
            CSharpTypeReference valueType = context.Symbols.ResolveTypeReference(typeName, typeSpecifier, declarator);
            PropertyDefinition valueProperty = new PropertyDefinition(
                name: XdrEmissionContext.GetUniquePropertyName(typeName, "Value", new HashSet<string>(StringComparer.Ordinal)),
                wireName: declarator.Identifier,
                typeReference: valueType,
                valueDescriptor: context.Symbols.ResolveCodecValueDescriptor(typeName, typeSpecifier, declarator),
                declarator: declarator,
                summary: "Gets or sets the underlying XDR value.");
            List<PropertyDefinition> properties = new List<PropertyDefinition> { valueProperty };

            EmitClassType(
                typeName,
                "Represents the emitted XDR typedef <c>" + XdrEmissionContext.EscapeXml(typeName) + "</c>.",
                properties,
                writer => context.Codecs.AppendAliasCodecMembers(writer, typeName, valueProperty));
        }
    }
}
