namespace OpenNFS.XdrGen.Emission
{
    using System;
    using System.Collections.Generic;

    internal sealed class XdrEmissionCodecTypeEmitter
    {
        private readonly XdrEmissionContext context;
        private readonly XdrEmissionCodecMemberSupport members;

        internal XdrEmissionCodecTypeEmitter(XdrEmissionContext context)
        {
            this.context = context;
            members = new XdrEmissionCodecMemberSupport(context);
        }

        internal void EmitEnumCodecType(string typeName)
        {
            string codecTypeName = typeName + "_XdrCodec";
            CodeWriter writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#nullable enable");
            writer.AppendLine("#pragma warning disable CS8981");
            writer.AppendLine("namespace " + context.Mapping.OutputNamespace);
            writer.AppendLine("{");
            writer.AppendLine("    using System;");
            writer.AppendLine("    using OpenNFS.Rpc.Xdr;");
            writer.AppendLine();
            writer.AppendLine("    internal static class " + XdrEmissionContext.EscapeIdentifier(codecTypeName));
            writer.AppendLine("    {");
            writer.AppendLine("        public static void Write(XdrWriter writer, " + XdrEmissionContext.EscapeIdentifier(typeName) + " value)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(writer);");
            writer.AppendLine("            writer.WriteInt32((int)value);");
            writer.AppendLine("        }");
            writer.AppendLine();
            writer.AppendLine("        public static " + XdrEmissionContext.EscapeIdentifier(typeName) + " Read(XdrReader reader)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(reader);");
            writer.AppendLine("            return (" + XdrEmissionContext.EscapeIdentifier(typeName) + ")reader.ReadInt32();");
            writer.AppendLine("        }");
            writer.AppendLine("    }");
            writer.AppendLine("}");
            writer.AppendLine("#pragma warning restore CS8981");

            context.AddGeneratedFile(codecTypeName, typeName + ".XdrCodec.g.cs", writer.ToString());
        }

        internal void AppendAliasCodecMembers(CodeWriter writer, string typeName, PropertyDefinition valueProperty)
        {
            writer.AppendLine();
            AppendWriteMethodDocumentation(writer);
            writer.AppendLine("        public void WriteTo(XdrWriter writer)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(writer);");
            members.EmitWriteMember(writer, "this." + XdrEmissionContext.EscapeIdentifier(valueProperty.Name), typeName + "." + valueProperty.Name, valueProperty, "writer", 3);
            writer.AppendLine("        }");
            writer.AppendLine();
            AppendReadMethodDocumentation(writer, typeName);
            writer.AppendLine("        public static " + XdrEmissionContext.EscapeIdentifier(typeName) + " ReadFrom(XdrReader reader)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(reader);");
            writer.AppendLine("            " + XdrEmissionContext.EscapeIdentifier(typeName) + " value = new " + XdrEmissionContext.EscapeIdentifier(typeName) + "();");
            members.EmitReadMember(writer, "value." + XdrEmissionContext.EscapeIdentifier(valueProperty.Name), valueProperty, "reader", 3);
            writer.AppendLine("            return value;");
            writer.AppendLine("        }");
        }

        internal void AppendStructCodecMembers(CodeWriter writer, string typeName, IReadOnlyList<PropertyDefinition> properties)
        {
            writer.AppendLine();
            AppendWriteMethodDocumentation(writer);
            writer.AppendLine("        public void WriteTo(XdrWriter writer)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(writer);");

            foreach (PropertyDefinition property in properties)
            {
                members.EmitWriteMember(writer, "this." + XdrEmissionContext.EscapeIdentifier(property.Name), typeName + "." + property.Name, property, "writer", 3);
            }

            writer.AppendLine("        }");
            writer.AppendLine();
            AppendReadMethodDocumentation(writer, typeName);
            writer.AppendLine("        public static " + XdrEmissionContext.EscapeIdentifier(typeName) + " ReadFrom(XdrReader reader)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(reader);");
            writer.AppendLine("            " + XdrEmissionContext.EscapeIdentifier(typeName) + " value = new " + XdrEmissionContext.EscapeIdentifier(typeName) + "();");

            foreach (PropertyDefinition property in properties)
            {
                members.EmitReadMember(writer, "value." + XdrEmissionContext.EscapeIdentifier(property.Name), property, "reader", 3);
            }

            writer.AppendLine("            return value;");
            writer.AppendLine("        }");
        }

        internal void AppendUnionCodecMembers(
            CodeWriter writer,
            string typeName,
            PropertyDefinition discriminantProperty,
            IReadOnlyList<UnionArmDefinition> arms)
        {
            writer.AppendLine();
            AppendWriteMethodDocumentation(writer);
            writer.AppendLine("        public void WriteTo(XdrWriter writer)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(writer);");

            string discriminantTypeName = discriminantProperty.TypeReference.NonNullableDisplayName;
            string discriminantAccess = "this." + XdrEmissionContext.EscapeIdentifier(discriminantProperty.Name);
            string discriminantContext = typeName + "." + discriminantProperty.Name;
            string discriminantValueExpression = discriminantProperty.ValueDescriptor.IsValueType && discriminantProperty.TypeReference.IsNullable
                ? "XdrGeneratedCodec.RequireValue(" + discriminantAccess + ", \"" + discriminantContext + "\")"
                : discriminantAccess;

            writer.AppendLine("            " + discriminantTypeName + " discriminant = " + discriminantValueExpression + ";");
            members.EmitWriteScalarCore(writer, "discriminant", discriminantContext, discriminantProperty, "writer", 3);

            if (arms.Count > 0)
            {
                writer.AppendLine("            switch (discriminant)");
                writer.AppendLine("            {");

                foreach (UnionArmDefinition arm in arms)
                {
                    AppendUnionCaseLabels(writer, discriminantProperty, arm);
                    members.EmitWriteMember(writer, "this." + XdrEmissionContext.EscapeIdentifier(arm.Property.Name), typeName + "." + arm.Property.Name, arm.Property, "writer", 5);
                    writer.AppendLine("                    break;");
                }

                writer.AppendLine("            }");
            }

            writer.AppendLine("        }");
            writer.AppendLine();
            AppendReadMethodDocumentation(writer, typeName);
            writer.AppendLine("        public static " + XdrEmissionContext.EscapeIdentifier(typeName) + " ReadFrom(XdrReader reader)");
            writer.AppendLine("        {");
            writer.AppendLine("            ArgumentNullException.ThrowIfNull(reader);");
            writer.AppendLine("            " + XdrEmissionContext.EscapeIdentifier(typeName) + " value = new " + XdrEmissionContext.EscapeIdentifier(typeName) + "();");
            writer.AppendLine("            " + discriminantTypeName + " discriminant = " + members.BuildReadScalarExpression(discriminantProperty, "reader") + ";");
            writer.AppendLine("            value." + XdrEmissionContext.EscapeIdentifier(discriminantProperty.Name) + " = discriminant;");

            if (arms.Count > 0)
            {
                writer.AppendLine("            switch (discriminant)");
                writer.AppendLine("            {");

                foreach (UnionArmDefinition arm in arms)
                {
                    AppendUnionCaseLabels(writer, discriminantProperty, arm);
                    members.EmitReadMember(writer, "value." + XdrEmissionContext.EscapeIdentifier(arm.Property.Name), arm.Property, "reader", 5);
                    writer.AppendLine("                    break;");
                }

                writer.AppendLine("            }");
            }

            writer.AppendLine("            return value;");
            writer.AppendLine("        }");
        }

        private void AppendUnionCaseLabels(CodeWriter writer, PropertyDefinition discriminantProperty, UnionArmDefinition arm)
        {
            if (arm.IsDefault)
            {
                writer.AppendLine("                default:");
                return;
            }

            foreach (string caseLabel in arm.CaseLabels)
            {
                writer.AppendLine("                case " + context.Symbols.ResolveUnionCaseLabel(discriminantProperty, caseLabel) + ":");
            }
        }

        private static void AppendWriteMethodDocumentation(CodeWriter writer)
        {
            writer.AppendLine("        /// <summary>");
            writer.AppendLine("        /// Writes the current instance to an XDR writer.");
            writer.AppendLine("        /// </summary>");
            writer.AppendLine("        /// <param name=\"writer\">The XDR writer to receive the encoded payload.</param>");
        }

        private static void AppendReadMethodDocumentation(CodeWriter writer, string typeName)
        {
            writer.AppendLine("        /// <summary>");
            writer.AppendLine("        /// Reads an instance of <see cref=\"" + XdrEmissionContext.EscapeIdentifier(typeName) + "\"/> from an XDR reader.");
            writer.AppendLine("        /// </summary>");
            writer.AppendLine("        /// <param name=\"reader\">The XDR reader supplying the encoded payload.</param>");
            writer.AppendLine("        /// <returns>The decoded instance.</returns>");
        }
    }
}
