<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Internal NFSv3, MOUNT v3, NLM v4, and NSM protocol implementation for OpenNFS.</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenNFS.Rpc\OpenNFS.Rpc.csproj" />
    <ProjectReference Include="..\OpenNFS.Server\OpenNFS.Server.csproj" />
  </ItemGroup>
</Project>
