<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Automated Touchstone runner project for OpenNFS.</Description>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Test.Shared\Test.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Touchstone.Cli" />
  </ItemGroup>
</Project>
