<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Internal NFSv4.2 protocol implementation for OpenNFS.</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\OpenNFS.Server\Internal\V42\*.cs" Link="Internal\V42\%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenNFS.Protocol.V41\OpenNFS.Protocol.V41.csproj" />
    <ProjectReference Include="..\OpenNFS.Rpc\OpenNFS.Rpc.csproj" />
    <ProjectReference Include="..\OpenNFS.Server\OpenNFS.Server.csproj" />
  </ItemGroup>
</Project>
