<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Internal NFSv4.2 protocol implementation for OpenNFS.</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenNFS.Rpc\OpenNFS.Rpc.csproj" />
  </ItemGroup>
</Project>
