<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.14.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="Touchstone.Cli" Version="0.1.12" />
    <PackageVersion Include="Touchstone.Core" Version="0.1.12" />
    <PackageVersion Include="Touchstone.NunitAdapter" Version="0.1.12" />
    <PackageVersion Include="Touchstone.XunitAdapter" Version="0.1.12" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>

